unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -as terminal-features ',xterm-256color:RGB'
set -g mouse on
set -g status-style bg=default
set -g pane-border-style default
set -g pane-active-border-style default
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set -g status-position top

bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

set -s escape-time 0

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @yank_with_mouse off

set -g default-shell /usr/bin/zsh

run '~/.tmux/plugins/tpm/tpm'

